### ISSUE TITLE
Container keeps restarting before i can finish config

### ISSUE THREAD

**Issue by espensgr** [wiserain/docker-rclone#9]
I'm trying to make a setup like in this [post](https://blog.muffn.io/unlimited-plex-storage-via-google-drive-and-rclone/), and started the config but keep getting kicked out of the terminal because the container keeps restarting.

the docker log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 10-adduser: executing... 


GID/UID

-------------------------------------

User uid:    1000

User gid:    1000

-------------------------------------


[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 40-config: executing... 

[cont-init.d] 40-config: exited 0.

[cont-init.d] 50-rclone: executing... 

*** checking rclone.conf

Waiting for rclone configuration file in /config/rclone.conf. Retrying in 30s ...

RUN: docker exec -it <DOCKER_CONTAINER> rclone_setup

Waiting for rclone configuration file in /config/rclone.conf. Retrying in 30s ...

RUN: docker exec -it <DOCKER_CONTAINER> rclone_setup
```
It loops through the last two lines over and over.

Here is my setup in the docker-compose
```
  rclone:
    container_name: rclone
    image: wiserain/rclone
    restart: always
    network_mode: "bridge"
    privileged: true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
#      - RCLONE_REMOTE_PATH=gmedia-crypt:/cloud
    volumes:
      - $ROOT/config/rclone:/config
      - $ROOT/config/rclone/logs:/log
      - $ROOT/cache/rclone:/cache
#      - $ROOT/config/rclone/mounts/gmedia-crypt:/cloud:shared
      - $ROOT/config/rclone/mounts/gmedia-local:/local:shared     # Optional: if you have a folder to be mergerfs/unionfs with
      - $ROOT/media:/data:shared
    devices:
      - /dev/fuse
    cap_add:
      - MKNOD
      - SYS_ADMIN
```
Is it a bug in the docker image or in my setup?
